### ISSUE TITLE
Mobile Editor Issues

### ISSUE THREAD

**Issue by ap0l0** [ziaahsan/template-builder#1]
hey, this UI looks great! is there a way to adapt it to be able to edit from mobile devices? I see GrapeJS have the touch plugin but the Editor UI still isn't compatible with phones

**Comment by ziaahsan** [comment]
@ap0l0 Thank you. Please note that I have no plans for this editor as of now.

I see that there was an issue regarding this https://github.com/artf/grapesjs/issues/1673. However, nothing came of it. 
You can try https://github.com/artf/grapesjs-touch based on the comments; Which I think you already have.

Best of luck!
